export const ASSETS_URL = import.meta.env.VITE_APP_ASSET;
export const ADMIN_ASSETS = import.meta.env.VITE_ADMIN_IMAGES;
export const ADMIN_ROOT = import.meta.env.VITE_APP_ADMIN_ROOT;
export const ADMIN_IMG_URL = import.meta.env.VITE_APP_ADMIN_IMAGE_URL;
export const API_URL = import.meta.env.VITE_APP_API_URL;
// export const BASE_URL = import.meta.env.VITE_APP_BASE_URL
export const VITE_APP_STORAGE = import.meta.env.VITE_APP_STORAGE_URL
export const TOKEN = localStorage.getItem('token');
export const BASE_ROOT = import.meta.env.VITE_APP_BASE_ROOT;
export const APP_PUBLIC_IMAGES = import.meta.env.VITE_APP_PUBLIC_IMAGES;
